### ISSUE TITLE
Allow relative paths for sources

### ISSUE THREAD

**Issue by riccardoporreca** [conda/conda-lock#229]
Since #189, paths stored in the lockfile are stored as absolute, to address the issue in #175 where the lockfile and the sources are not on the same drive.

However, there was probably a point in relative paths and the change has its drawback for other (more common?). Consider sources and lockfiles maintained under version control in the same repo: one wouldn't want to produce and push lockfiles containing references to the absolute path of the local checkout.

I think using absolute paths should be opt-in, or used in case the construction of relative paths does not work.

**Comment by riccardoporreca** [comment]
A sensible approach might be to restore the old behavior unless the source path is absolute, so absolute source paths (possibly including the drive) would stay as absolute. This should still address #175 but keep the (more sensible?) behavior for the other cases

**Comment by riccardoporreca** [comment]
Actually, #189 might have introduced an inconsistency with the logic (from https://github.com/conda-incubator/conda-lock/pull/124/commits/df566dcfdd1ba4e127efe27649748a088b573d97) for reconstructing the source file path from the lock file itself if not specified

https://github.com/conda-incubator/conda-lock/blob/7d9bd6d67d59fdd30d92a2ace3ee344aafa6a2b1/conda_lock/conda_lock.py#L920-L932

which is probably broken: I haven't tested it, but I assume "reconstruct native paths" would fail for absolute paths in `lock_content.metadata.sources`.

I think the "sensible approach" hinted above would be easily to mirror in a consistent way in this logic as well. I will try to draft a PR.

**Comment by JessicaS11** [comment]
Just wanted to leave a note that I support an opt-in (or at the very least optional) use of absolute paths. In our use case, we have multiple contributors who might update the lock files locally, and with absolute paths `conda-lock.yml` lists each person's local path as source (rather than just the shared environment.yml). Thanks for working on an update for this!

**Comment by maresb** [comment]
@JessicaS11 I'm curious about your use case for opt-in of absolute paths. Would you want the path to the source file `environment.yml` to be absolute, or the `conda-lock.yml` in the comment header, or both?
