### ISSUE TITLE
Bad url to Docs 

### ISSUE THREAD

**Issue by cerodell** [conda/conda-lock#326]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The url to your docs page is incorrect. Was able to find it by removing `-incubator`. So...

`https://conda-incubator.github.io/conda-lock` ----> `https://conda.github.io/conda-lock`

Cheers,
Chris

**Comment by maresb** [comment]
Hi, thanks for the report! Yes, we just moved this repository from incubator to main. You don't specify exactly where this incorrect URL occurs, but would https://github.com/conda/conda-lock/pull/324 fix this issue? (We really should get that merged and rereleased.)
