### ISSUE TITLE
Drop support for Python 3.6 and 3.7

### ISSUE THREAD

**Issue by maresb** [conda/conda-lock#329]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Ease development through use of modern Python

### Why is this needed?

Working with type annotations becomes much easier when I can use `from __future__ import annotations`

### What should happen?

Bump minimal Python version to 3.7

### Additional Context

Any thoughts, @bollwyvl?

**Comment by bollwyvl** [comment]
Drop 3.7, too?

**Comment by maresb** [comment]
> Drop 3.7, too?

I didn't want to be too radical, but yes! :smile:

**Comment by maresb** [comment]
> Drop 3.7, too?

I didn't want to be too radical, but yes! :smile:
