### ISSUE TITLE
Cut a post-graduation conda-org release

### ISSUE THREAD

**Issue by maresb** [conda/conda-lock#336]
It would be nice to do a release to iron out any issues related to graduation.

There were several very minor changes merged into `main`. The only breaking change is dropping support for Python 3.6 and 3.7 (which is easily revertible in case of objections.)

Does this deserve a minor release (`v1.4.0`→`v1.5.0`)?

It looks like the docs are already updating on push, so I think the only major question is PyPI? It seems currently driven by GHA [`secrets.PYPI_PASSWORD`](https://github.com/conda/conda-lock/blob/d04563cd8f2001e64316eb46975781bcda29d9ce/.github/workflows/release.yaml#L45), so I wonder if this secret carried over.

There's also this file `github_deploy_key_mariusvniekerk_conda_lock.enc` set up by @ocefpaf which looks like a relic from Travis CI. Can it be safely deleted?

@ocefpaf, would you be able to help with a release?

**Comment by ocefpaf** [comment]
> It looks like the docs are already updating on push, so I think the only major question is PyPI? It seems currently driven by GHA [`secrets.PYPI_PASSWORD`](https://github.com/conda/conda-lock/blob/d04563cd8f2001e64316eb46975781bcda29d9ce/.github/workflows/release.yaml#L45), so I wonder if this secret carried over.

I believe this will work. Marius ironed out the last detail in https://github.com/conda/infrastructure/issues/686

> There's also this file `github_deploy_key_mariusvniekerk_conda_lock.enc` set up by @ocefpaf which looks like a relic from Travis CI. Can it be safely deleted?

Yep. Done in #344 

> @ocefpaf, would you be able to help with a release?

Sure. Let me know when you are ready.

**Comment by lesteve** [comment]
A release would be great! My particular interest is https://github.com/conda/conda-lock/pull/295. Anyone that has `jupyter-server` in a pip section is affected by this bug that causes a Windows-specific dependency to find its way into the lock file.

Of course I can use the conda-lock development version, but a release would be great!

**Comment by maresb** [comment]
Hey @ocefpaf, if you're available, then let's make today v2.0.0 release day!
