### ISSUE TITLE
Release notes for conda-lock v2

### ISSUE THREAD

**Issue by borchero** [conda/conda-lock#424]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

`conda-lock` v2 has been published a couple days ago and it would be great to have a summary what changed compared to v1.

### Why is this needed?

While there is a changelog associated with the release, it is very fine-grained and, as a user, it is not clear why these changes warrant a major version bump.

### What should happen?

It would be great to at least add a "highlights" section to the release notes of release v2.0.0. Also, if there are notable API changes, it would be great to see some examples.

**Comment by maresb** [comment]
Thanks a lot for the feedback @borchero. I quickly threw together a "Summary" section at the beginning of the [release notes](https://github.com/conda/conda-lock/releases/tag/v2.0.0). Is this sufficient, or should there be more?

**Comment by borchero** [comment]
Thanks a lot for the quick implementation @maresb! For me, this is sufficient :)
