### ISSUE TITLE
conda-lock is incompatible with pydantic 2

### ISSUE THREAD

**Issue by pavelzw** [conda/conda-lock#472]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have conda-lock installed via `brew` (it uses pydantic 2 for the build) and when I enter `conda-lock render --help`, I get the following warnings:

```
❯ conda-lock render --help
/opt/homebrew/Cellar/conda-lock/2.1.1/libexec/lib/python3.11/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'json_encoders' has been removed
  warnings.warn(message, UserWarning)
/opt/homebrew/Cellar/conda-lock/2.1.1/libexec/lib/python3.11/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'allow_mutation' has been removed
  warnings.warn(message, UserWarning)
Usage: conda-lock render [OPTIONS] [LOCK_FILE]
[...]
```

**Comment by maresb** [comment]
Thanks for the report!

These warning should be just warnings.

We have a fix in #459 for the next release.

Are you able to ignore the warnings? If you discover any malfunctions as a result, then please let us know!

**Comment by pavelzw** [comment]
Yes, sure!

**Comment by maresb** [comment]
Let's leave this open for visibility until we release #459.
