### ISSUE TITLE
Check if lockfile is stale without attempting a new solve

### ISSUE THREAD

**Issue by calebzulawski** [conda/conda-lock#534]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I would like to be able to check if a lockfile is stale (like `--check-input-hash`) without actually solving the environment if it is stale.

### Why is this needed?

This is useful for simply validating a lockfile in CI/CD

**Comment by calebzulawski** [comment]
Nevermind, I see this is covered by #479

**Comment by maresb** [comment]
See also #432

**Comment by maresb** [comment]
I'm going consider this as a duplicate of https://github.com/conda/conda-lock/issues/432
