### ISSUE TITLE
Spurious warning when running conda-lock install

### ISSUE THREAD

**Issue by psarka** [conda/conda-lock#544]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Whenever I'm running conda-lock install, I get the following warning displayed:

```
WARNING:conda_lock.conda_lock:WARNING: installation of pip dependencies is only supported by the 'conda-lock install' and 'micromamba install' commands. Other tools may silently ignore them. For portability, we recommend using the newer unified lockfile format (i.e. removing the --kind=explicit argument.
```

I don't understand what it want's from me, as the lock file was produced by running `conda-lock`without the --kind=explicit flag. 

And in any case, I'm a happy user of conda-lock & micromamba, and I really don't care about inferior tools getting things wrong :P

### Additional Context

I've seen this warning in conda-lock versions, including the latest 2.4.2.

**Comment by maresb** [comment]
Ah, thanks for pointing this out!

This warning was intended to be emitted only when running `conda-lock --kind=explicit`. Internally, `conda-lock install` renders explicit for installing the conda deps. We should be suppressing the warning in this case!
