### ISSUE TITLE
Password supplied via environment variable in `environment.yaml` is expanded in `conda-lock.yml`

### ISSUE THREAD

**Issue by wholtz** [conda/conda-lock#594]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have an `environment.yaml`:

```
name: base
platforms:
  - linux-64
channels:
  - conda-forge
pip-repositories:
  - https://aws:$CODEARTIFACT_PASSWORD@sanitized-example.d.codeartifact.us-west-2.amazonaws.com/pypi/sanitized/simple/
dependencies:
  - python=3.9
  - pip
  - pip:
      - privatepackage==1.2.3
 ```

and I run:

```
conda-lock lock -f environment.yaml
```

The resulting `conda-lock.yml` contains the expanded value of the `$CODEARTIFACT_PASSWORD` environmental variable. I expected this environment variable would not be expanded in the `conda-lock.yml/`

### Conda Info

```shell
I don't have conda or mamba installed. Only micromamba.
micromamba info 

       libmamba version : 1.5.3
     micromamba version : 1.5.3
           curl version : libcurl/8.4.0 SecureTransport (OpenSSL/3.1.4) zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /Users/willholtz/micromamba/envs
          package cache : /Users/willholtz/micromamba/pkgs
                          /Users/willholtz/.mamba/pkgs
            environment : None (not found)
           env location : -
      user config files : /Users/willholtz/.mambarc
 populated config files :
       virtual packages : __unix=0=0
                          __osx=14.2.1=0
                          __archspec=1=arm64
               channels :
       base environment : /Users/willholtz/micromamba
               platform : osx-arm64
```

### Conda Config

```shell
micromamba  config sources
Configuration files (by precedence order):
```

### Conda list

```shell
micromamba list
List of packages in environment: ""
```

### Additional Context

I also tried supplying the the environmental variable inside `{}`:

```
  - https://aws:${CODEARTIFACT_PASSWORD}@sanitized-example.d.codeartifact.us-west-2.amazonaws.com/pypi/sanitized/simple/
 ```

but there was no change in observed behavior.

**Comment by maresb** [comment]
Oh, that's bad. Thanks for the report. I will try to figure out what's going on.

**Comment by maresb** [comment]
I'd like a reproducer that doesn't strictly rely on a private pypi repo. I tried this but failed to reproduce the problem:

```
name: base
platforms:
  - linux-64
channels:
  - conda-forge
pip-repositories:
  - https://$USER:$PASS@pypi.org/simple/
dependencies:
  - python=3.9
  - pip
  - pip:
      - cowsay
```

**Comment by maresb** [comment]
Reference: https://github.com/conda/conda-lock/pull/529

Noteworthy is the mock private pypi.

**Comment by maresb** [comment]
Still trying to figure out what's going on. This problem should have been caught by this test:

https://github.com/conda/conda-lock/blob/2c2999bb9805dbc4abe46e38f7d70d038728b31c/tests/test_pip_repositories.py#L164-L172

@jacksmith15, do you have any insights?

**Comment by wholtz** [comment]
I've been executing my lock file generation in parallel to the test `test_it_uses_pip_repositories_with_env_var_substitution[micromamba]` to see where there is some divergence in the env var being in the URL vs the expanded value. Before line https://github.com/conda/conda-lock/blob/431c09b2cc7e1c9ab7bda6c5b37c87083a000572/conda_lock/pypi_solver.py#L361 they appear to be similar, but the value of `link` diverges.

From the test:
```
<Link http://private-pypi.org/files/fake-private-package-1.0.0.tar.gz (from <conda_lock._vendor.poetry.repositories.legacy_repository.Page object at 0x109aa3c50>)>
```

From my case:
```
<Link https://aws:*************@sanitized-example.d.codeartifact.us-west-2.amazonaws.com/pypi/sanatized/simple/tabulate/0.9.0/tabulate-0.9.0-py3-none-any.whl#sha256=024ca478df22e9340661486f85298cff5f6dcdba14f3813e8830015b9ed1948f (from <conda_lock._vendor.poetry.repositories.legacy_repository.Page object at 0x107a882d0>) (requires-python:>=3.7)>
```

Where the `************` is actually my password.
